[variables]
    DOTNET_ROOT = '/usr/share/dotnet'

[phases.setup]
    nixPkgs = ['dotnet-sdk_8']

[phases.build]
    # Aqui for√ßamos o build apontando para o seu .slnx ou para o .csproj da API
    cmds = ['dotnet publish ./src/DesafioMinervaFoods.slnx -c Release -o out']

[start]
    # Ajuste o nome da DLL para o nome real do seu projeto de API
    cmd = 'dotnet out/DesafioMinervaFoods.API.dll'
