name: CI/CD Desafio Minerva Foods - Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/DesafioMinervaFoods.Front/**'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: ğŸ— Checkout repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './src/DesafioMinervaFoods.Front/package-lock.json'

      - name: ğŸ“¦ Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./src/DesafioMinervaFoods.Front

      - name: ğŸš€ Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}         

      - name: ğŸš€ Publish Update (Deploy)
        working-directory: ./src/DesafioMinervaFoods.Front
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          # O segredo para o Expo enxergar variÃ¡veis em tempo de build/update
          EXPO_PUBLIC_API_URL: ${{ secrets.API_URL_RAILWAY }}
        run: |
          npm install -g eas-cli
          # Garante que o EAS estÃ¡ configurado e faz o update
          eas update --auto --branch production --non-interactive
